//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_AdditionalShiftRequests
    {
        public int id_additionalShiftRequest { get; set; }
        public int id_assignment { get; set; }
        public int id_department { get; set; }
        public int Date { get; set; }
        public int id_shiftType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
    
        public virtual NM_ShiftTypes NM_ShiftTypes { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
        public virtual UN_Departments UN_Departments { get; set; }
        public virtual HR_Assignments HR_Assignments { get; set; }
    }
}
