//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_BranchMovements
    {
        public int id_branchMovement { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> id_departmentTo { get; set; }
        public int id_presenceForm { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool IsActive { get; set; }
        public int id_userLogin { get; set; }
    
        public virtual GR_PresenceForms GR_PresenceForms { get; set; }
        public virtual UN_Departments UN_Departments { get; set; }
    }
}
