//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_CrewMembers
    {
        public int id_crewMember { get; set; }
        public int id_assignment { get; set; }
        public int id_crew { get; set; }
    
        public virtual GR_Crews GR_Crews { get; set; }
        public virtual HR_Assignments HR_Assignments { get; set; }
    }
}
