//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_Crews2
    {
        public int id_crew { get; set; }
        public int id_department { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public int Name { get; set; }
        public int id_crewType { get; set; }
        public Nullable<int> id_assignment1 { get; set; }
        public Nullable<int> id_assignment2 { get; set; }
        public Nullable<int> id_assignment3 { get; set; }
        public Nullable<int> id_assignment4 { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public bool IsTemporary { get; set; }
    
        public virtual HR_Assignments HR_Assignments { get; set; }
        public virtual HR_Assignments HR_Assignments1 { get; set; }
        public virtual HR_Assignments HR_Assignments2 { get; set; }
        public virtual HR_Assignments HR_Assignments3 { get; set; }
        public virtual UN_Departments UN_Departments { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
    }
}
