//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_DriverAmbulances
    {
        public int id_driverAmbulance { get; set; }
        public int id_driverAssignment { get; set; }
        public int id_primaryAmbulance { get; set; }
        public int id_secondaryAmbulance { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime PrimaryAmbulanceFrom { get; set; }
        public System.DateTime PrimaryAmbulanceTo { get; set; }
        public System.DateTime SecondaryAmbulanceFrom { get; set; }
        public System.DateTime SecondaryAmbulanceTo { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
    
        public virtual GR_Ambulances GR_Ambulances { get; set; }
        public virtual GR_Ambulances GR_Ambulances1 { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
        public virtual HR_Assignments HR_Assignments { get; set; }
    }
}
