//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_DepartmentSchedules
    {
        public int id_departmentSchedule { get; set; }
        public System.DateTime Date { get; set; }
        public int id_department { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public Nullable<int> id_day1 { get; set; }
        public Nullable<int> id_day2 { get; set; }
        public Nullable<int> id_day3 { get; set; }
        public Nullable<int> id_day4 { get; set; }
        public Nullable<int> id_day5 { get; set; }
        public Nullable<int> id_day6 { get; set; }
        public Nullable<int> id_day7 { get; set; }
        public Nullable<int> id_day8 { get; set; }
        public Nullable<int> id_day9 { get; set; }
        public Nullable<int> id_day10 { get; set; }
        public Nullable<int> id_day11 { get; set; }
        public Nullable<int> id_day12 { get; set; }
        public Nullable<int> id_day13 { get; set; }
        public Nullable<int> id_day14 { get; set; }
        public Nullable<int> id_day15 { get; set; }
        public Nullable<int> id_day16 { get; set; }
        public Nullable<int> id_day17 { get; set; }
        public Nullable<int> id_day18 { get; set; }
        public Nullable<int> id_day19 { get; set; }
        public Nullable<int> id_day20 { get; set; }
        public Nullable<int> id_day21 { get; set; }
        public Nullable<int> id_day22 { get; set; }
        public Nullable<int> id_day23 { get; set; }
        public Nullable<int> id_day24 { get; set; }
        public Nullable<int> id_day25 { get; set; }
        public Nullable<int> id_day26 { get; set; }
        public Nullable<int> id_day27 { get; set; }
        public Nullable<int> id_day28 { get; set; }
        public Nullable<int> id_day29 { get; set; }
        public Nullable<int> id_day30 { get; set; }
        public Nullable<int> id_day31 { get; set; }
    
        public virtual UN_Departments UN_Departments { get; set; }
    }
}
