//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_PresenceForms
    {
        public int id_presenceForm { get; set; }
        public System.DateTime Date { get; set; }
        public int id_assignment { get; set; }
        public int id_shiftType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public Nullable<int> id_crew { get; set; }
    
        public virtual NM_ShiftTypes NM_ShiftTypes { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
        public virtual GR_Crews GR_Crews { get; set; }
        public virtual HR_Assignments HR_Assignments { get; set; }
    }
}
