//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_StartShifts
    {
        public int id_startShifts { get; set; }
        public int ShiftsNumber { get; set; }
        public int StartShift { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
