//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_SixMonthPlans
    {
        public int id_sixMonthPlan { get; set; }
        public int id_crew { get; set; }
        public int id_assignment { get; set; }
        public System.DateTime Date { get; set; }
        public int id_shiftType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
    }
}
