//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_ShiftAssignments
    {
        public int id_shiftAssignment { get; set; }
        public int id_assignment { get; set; }
        public int id_departmentShift { get; set; }
        public int id_userLogin { get; set; }
        public System.DateTime Timestamp { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
    
        public virtual GR_DepartmentShifts GR_DepartmentShifts { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
        public virtual HR_Assignments HR_Assignments { get; set; }
    }
}
