//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_WorkTimeAbsence
    {
        public int id_worktimeAbsence { get; set; }
        public int id_contract { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsPresence { get; set; }
        public string Reasons { get; set; }
        public Nullable<double> PrevMonthHours { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CourseNumber { get; set; }
        public string RegNumber { get; set; }
        public Nullable<bool> IsGPSMatch { get; set; }
        public Nullable<System.DateTime> GPSEndHour { get; set; }
        public Nullable<int> id_ambulance { get; set; }
        public double WorkHours { get; set; }
        public bool IsPrevMonthTransfer { get; set; }
    
        public virtual HR_Contracts HR_Contracts { get; set; }
        public virtual GR_Ambulances GR_Ambulances { get; set; }
    }
}
