//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_WorkHours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GR_WorkHours()
        {
            this.HR_Assignments = new HashSet<HR_Assignments>();
            this.GR_Ambulances = new HashSet<GR_Ambulances>();
        }
    
        public int id_workHours { get; set; }
        public string DayHours { get; set; }
        public Nullable<System.TimeSpan> DayStart { get; set; }
        public Nullable<System.TimeSpan> DayEnd { get; set; }
        public string NightHours { get; set; }
        public Nullable<System.TimeSpan> NightStart { get; set; }
        public Nullable<System.TimeSpan> NightEnd { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public bool IsSumWorkTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Assignments> HR_Assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_Ambulances> GR_Ambulances { get; set; }
    }
}
