//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_YearHolidays
    {
        public int id_yearHoliday { get; set; }
        public int Name { get; set; }
        public int Total { get; set; }
        public int Leftover { get; set; }
        public int id_contract { get; set; }
        public bool IsActive { get; set; }
        public int id_userLogin { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual HR_Contracts HR_Contracts { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
    }
}
