//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_YearWorkDays
    {
        public int id_yearWorkDay { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsWorkDay { get; set; }
        public bool IsNationalHoliday { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
    
        public virtual UN_UserLogins UN_UserLogins { get; set; }
    }
}
