//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_AuditLog
    {
        public int id_log { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public int PrimaryKeyID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime DateChanged { get; set; }
        public int id_userLogin { get; set; }
        public string Operation { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
