//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_DepartmentTree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UN_DepartmentTree()
        {
            this.UN_DepartmentTree1 = new HashSet<UN_DepartmentTree>();
        }
    
        public int id_departmentTree { get; set; }
        public Nullable<int> id_departmentParent { get; set; }
        public int id_department { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int id_userLogin { get; set; }
        public int TreeOrder { get; set; }
    
        public virtual UN_Departments UN_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UN_DepartmentTree> UN_DepartmentTree1 { get; set; }
        public virtual UN_DepartmentTree UN_DepartmentTree2 { get; set; }
        public virtual UN_UserLogins UN_UserLogins { get; set; }
    }
}
