//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_SystemSettings
    {
        public int id_systemSettings { get; set; }
        public int SystemStartShift { get; set; }
        public System.DateTime SystemStartShiftDate { get; set; }
    }
}
