//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_UserLogins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UN_UserLogins()
        {
            this.GR_AdditionalShiftRequests = new HashSet<GR_AdditionalShiftRequests>();
            this.HR_WorkTime = new HashSet<HR_WorkTime>();
            this.HR_YearWorkDays = new HashSet<HR_YearWorkDays>();
            this.NM_AbsenceTypes = new HashSet<NM_AbsenceTypes>();
            this.NM_MedicalSpecialities = new HashSet<NM_MedicalSpecialities>();
            this.HR_GlobalPositions = new HashSet<HR_GlobalPositions>();
            this.UN_Departments = new HashSet<UN_Departments>();
            this.HR_Contracts = new HashSet<HR_Contracts>();
            this.HR_Assignments = new HashSet<HR_Assignments>();
            this.HR_StructurePositions = new HashSet<HR_StructurePositions>();
            this.GR_ShiftTypes = new HashSet<GR_ShiftTypes>();
            this.HR_YearHolidays = new HashSet<HR_YearHolidays>();
            this.GR_PresenceForms = new HashSet<GR_PresenceForms>();
            this.GR_DriverAmbulances = new HashSet<GR_DriverAmbulances>();
            this.GR_Crews2 = new HashSet<GR_Crews2>();
            this.GR_Crews = new HashSet<GR_Crews>();
            this.HR_Absence = new HashSet<HR_Absence>();
        }
    
        public int id_userLogin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_person { get; set; }
        public int id_role { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_AdditionalShiftRequests> GR_AdditionalShiftRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_WorkTime> HR_WorkTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_YearWorkDays> HR_YearWorkDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NM_AbsenceTypes> NM_AbsenceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NM_MedicalSpecialities> NM_MedicalSpecialities { get; set; }
        public virtual NM_Roles NM_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_GlobalPositions> HR_GlobalPositions { get; set; }
        public virtual UN_Persons UN_Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UN_Departments> UN_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Contracts> HR_Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Assignments> HR_Assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_StructurePositions> HR_StructurePositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_ShiftTypes> GR_ShiftTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_YearHolidays> HR_YearHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_PresenceForms> GR_PresenceForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_DriverAmbulances> GR_DriverAmbulances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_Crews2> GR_Crews2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_Crews> GR_Crews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Absence> HR_Absence { get; set; }
    }
}
